### ISSUE TITLE
File dependencies containing .js extension causes it to ignore baseURL

### ISSUE THREAD

**Issue by JeroenVinke** [amodrojs/amodro-trace#7]
Hello,

We have recently come across an issue related to file dependencies that include the .js extension like so: `define(["./bar.js"], function (){})`. This causes requirejs to behave differently and it returns a file path that is incorrect (it is missing the baseUrl).

I have pushed a repro here: https://github.com/JeroenVinke/amodro-js-extension. Basically, `app.js` depends on `some-dir/foo.js` which depends on `some-dir/bar.js`. When `foo.js` declares its dependency on `bar.js` using the `.js` extension, the trace fails because the baseUrl is ignored. Removing the .js extension in `foo.js` resolves the issue.

Error:

> PS C:\Development\amdro-trace-js-extension> node index.js
C:/Development/amdro-trace-js-extension/src/app.js
C:/Development/amdro-trace-js-extension/src/some-dir/foo.js
C:/Development/amdro-trace-js-extension/some-dir/bar.js
{ Error: ENOENT: no such file or directory, open 'C:\Development\amdro-trace-js-extension\some-dir\bar.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at defaultRead (C:\Development\amdro-trace-js-extension\node_modules\amodro-trace\lib\loader\Loader.js:64:21)
    at fileRead (C:\Development\amdro-trace-js-extension\index.js:16:16)
    at Object.context.fileRead (C:\Development\amdro-trace-js-extension\node_modules\amodro-trace\lib\loader\Loader.js:176:18)
    at Object.context.load (C:\Development\amdro-trace-js-extension\node_modules\amodro-trace\lib\loader\Loader.js:357:30)
    at Module.load (eval at <anonymous> (C:\Development\amdro-trace-js-extension\node_modules\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:834:29)
    at Module.fetch (eval at <anonymous> (C:\Development\amdro-trace-js-extension\node_modules\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:824:66)
    at Module.check (eval at <anonymous> (C:\Development\amdro-trace-js-extension\node_modules\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:856:30)
    at Module.enable (eval at <anonymous> (C:\Development\amdro-trace-js-extension\node_modules\amodro-trace\lib\loader\Loader.js:14:1), <anonymous>:1176:22)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Development\\amdro-trace-js-extension\\some-dir\\bar.js',
  moduleTree: [ 'some-dir/foo' ],
  fileName: 'C:/Development/amdro-trace-js-extension/src/some-dir/foo.js' }

Here is a fix that has worked for us: https://github.com/JeroenVinke/cli/commit/e1e5441fbcc70f81880e8a103fa0579ff9d62684. We'd like to know if this is considered to be an acceptable solution.

Thanks for your work on this!

**Comment by jrburke** [comment]
I believe passing [nodeIdCompat: true](http://requirejs.org/docs/api.html#config-nodeIdCompat) to the loader config, should fix the issue:

```javascript
amodroTrace(
  // The options for trace
  {
    ...
  },
  // The AMD loader config to use.
  {
    ...,
    nodeIdCompat: true
  }
)
```

**Comment by JeroenVinke** [comment]
Thanks, will give that a shot! Now that you're back to getting releases out, I assume that [this situation](https://github.com/amodrojs/amodro-trace/issues/5#issuecomment-284127181) has been resolved. We have a few use cases that we'd like to create PR's for. One example is that we need amodrotrace to take the `browser` section of package.json's into account while doing traces. Would you be open to us creating PR's for these sorts of things?

**Comment by jrburke** [comment]
It is all sorted now. As far as using different rules for figuring out the file path for a module ID, at first thought, I would want it something like how fileRead and fileExists works, allow for an optional function that could change how the ID is turned into a file path.

**Comment by 3cp** [comment]
@JeroenVinke I was working on the date-fns bundling issue I asked you on gitter. It leads me here.
`nodeIdCompat:true` works! May I ask why it's not turned on in aurelia-cli yet?
